export const COMMANDS = {
  UP: 'up',
  CD: 'cd',
  LS: 'ls',
  CAT: 'cat',
  ADD: 'add',
  MKDIR: 'mkdir',
  RENAME: 'rn',
  COPY: 'cp',
  MOVE: 'mv',
  DELETE: 'rm',
  OS: 'os',
  HASH: 'hash',
  COMPRESS: 'compress',
  DECOMPRESS: 'decompress',
  EXIT: '.exit',
};

export const OS_FLAGS = {
  EOL: '--EOL',
  CPUS: '--cpus',
  HOMEDIR: '--homedir',
  USERNAME: '--username',
  ARCHITECTURE: '--architecture',
};

export const ERROR_MESSAGES = {
  INVALID_INPUT: 'Invalid input',
  OPERATION_FAILED: 'Operation failed',
  USERNAME_REQUIRED: 'Username is required. Please provide --username argument.',
  FILE_NOT_FOUND: 'File not found',
  DIRECTORY_NOT_FOUND: 'Directory not found',
  PATH_NOT_DIRECTORY: 'Path is not a directory',
  PATH_NOT_FILE: 'Path is not a file',
  FILE_ALREADY_EXISTS: 'File already exists',
  DIRECTORY_ALREADY_EXISTS: 'Directory already exists',
  DIRECTORY_PATH_REQUIRED: 'Directory path is required',
  FILE_NAME_REQUIRED: 'File name is required',
  DIRECTORY_NAME_REQUIRED: 'Directory name is required',
  NEW_NAME_REQUIRED: 'New name is required',
  SOURCE_NOT_FOUND: 'Source file or directory not found',
  DESTINATION_EXISTS: 'Destination already exists',
  CANNOT_COPY_TO_SELF: 'Cannot copy file to itself',
  DESTINATION_FILE_EXISTS: 'Destination file already exists',
  PARENT_NOT_DIRECTORY: 'Parent path is not a directory',
  CANNOT_ACCESS_PARENT: 'Cannot access parent directory',
  FAILED_TO_READ_FILE: 'Failed to read file',
  FAILED_TO_CREATE_FILE: 'Failed to create file',
  FAILED_TO_CREATE_DIRECTORY: 'Failed to create directory',
  FAILED_TO_RENAME: 'Failed to rename',
  FAILED_TO_COPY: 'Failed to copy file',
  FAILED_TO_MOVE: 'Failed to move file',
  FAILED_TO_DELETE: 'Failed to delete file',
  FAILED_TO_COMPRESS: 'Failed to compress file',
  FAILED_TO_DECOMPRESS: 'Failed to decompress file',
  FAILED_TO_CALCULATE_HASH: 'Failed to calculate hash',
  FAILED_TO_CHECK_DESTINATION: 'Failed to check destination',
  FAILED_TO_CREATE_DEST_DIR: 'Failed to create destination directory',
  CANNOT_READ_DIRECTORY: 'Cannot read directory',
  INVALID_OS_FLAG: 'Invalid OS flag',
  FILE_NOT_FOUND_OR_NOT_FILE: 'File not found or path is not a file',
  SOURCE_FILE_NOT_FOUND: 'Source file not found',
  DESTINATION_DIRECTORY_NOT_FOUND: 'Destination directory not found',
};

